import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex justify-between w-4/5 mx-auto pt-5">
          <div>
            <h1 className="font-bold text-2xl">Shop</h1>
          </div>
          <div className="flex  gap-4 font-bold">
            <Link href={"/"}>item</Link>
            <Link href={"/transaction"}>Transaction</Link>
            <Link href={"#"}>Dashboard</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
